listen: :50000
tls:
  cert: /etc/ssl/private/cert.pem
  key: /etc/ssl/private/privkey.pem
auth:
  type: password
  password: $HYSTERIA_PASSWORD
masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com
    rewriteHost: true
ignoreClientIP: true
bandwidth:
  up: 1 gbps
  down: 1 gbps
quic:
  initStreamReceiveWindow: 8388608
  maxStreamReceiveWindow: 8388608
  initConnectionReceiveWindow: 20971520
  maxConnectionReceiveWindow: 20971520
  maxIdleTimeout: 30s
  maxIncomingStreams: 1024
  disablePathMTUDiscovery: false
